server:
  port: 7005
  servlet:
    context-path: /ad-admin

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: ad-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.21.0.7:33061/tianzhuo_ad_data?autoReconnect=true
    #url: jdbc:mysql://49.232.91.191:33061/tianzhuo_ad_data?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: tianzhuo_admin
    password: Tianzhuo2021
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  redis:
    #    cluster:
    #      max-redirects: 3  # 获取失败 最大重定向次数
    #      nodes: 49.232.91.191:6379,81.70.178.200:6379,82.156.126.248:6379,49.232.74.185:6379,49.233.44.47:6379,152.136.194.147:6379
    #          password: 0UKPqK2u
    #      nodes: 8.140.99.234:7010,8.140.99.234:7011,8.140.99.234:7012,8.140.99.234:7013,8.140.99.234:7014,8.140.99.234:7015
    host: 172.21.0.44 #172.21.0.44  120.53.231.222
    port: 6379
    password: 0UKPqK2u
    database: 0
    timeout: 1000 #超时时间
    # 配置文件中添加 lettuce.pool 相关配置，则会使用到lettuce连接池
#    lettuce:
#      pool:
#        max-wait: 500 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 10 # 连接池中的最大空闲连接 默认 8
#        min-idle: 5 # 连接池中的最小空闲连接 默认 0
#        max-active: 10 # 连接池最大连接数（使用负值表示没有限制） 默认 8


tencent:
  appId: 1305375713
  secretId: AKIDiLlxZyXsNbYFTvMFXGljfPu9CTYONJs5
  secretKey: C9qLgndojSyyXrv6NFvPAf1C82C7nICw
  photoBucket: tz-1305375713
  region: ap-beijing

  kafka:
    bootstrap-servers: 47.104.173.250:9092
    template:
      default-topic: mykafka #topic 名
      listener:
        concurrency: 5 #指定listener 容器中的线程数，用于提高并发量
      consumer:
        group-id: myGroup # 指定默认消费者group id
        client-id: 200
        max-poll-records: 200
        auto-offset-reset: earliest # 最早未被消费的offset
      producer:
        batch-size: 1000 # 每次批量发送消息的数量
        retries: 3
        client-id: 200

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://172.21.0.8:8008/eureka/,http://172.21.0.20:8008/eureka/,http://172.21.0.22:8008/eureka/,http://172.21.0.24:8008/eureka/,http://172.21.0.29:8008/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    max-size: 50MB # 日志文件的最大大小。默认为 20MB
    max-history: 1 # 日志文件要保留的归档的最大天数。默认为 7 天
  path: logs
  level:
    root: info
    com.tianzhuo.ad.mapper: debug

ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 9000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000